source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'GKActionSheetPicker_Example', :exclusive => true do
  pod "GKActionSheetPicker", :path => "../"
end

target 'GKActionSheetPicker_Tests', :exclusive => true do
  pod "GKActionSheetPicker", :path => "../"

  
end
