source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '9.0'

target 'GKActionSheetPicker_Example' do
  pod "GKActionSheetPicker", :path => "../"
end

target 'GKActionSheetPicker_Tests' do
  pod "GKActionSheetPicker", :path => "../"
end
